server:
  port: ${PORT:8081}

spring:
  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: admin
    initialization-mode: always
    continue-on-error: true
    plataform: postgressql

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  main:
    allow-circular-references: true

